[package]
name = "rchat_client"
version = "0.1.0"
authors = ["mmihira <mmihira.w@gmail.com>"]

[dependencies]
msg_protocol = { path= "./../msg_protocol/" }
serde_json = "1.0"
uuid = { version = "0.6", features = ["v4"] }
