[package]
name = "rchat_client"
version = "0.1.0"
authors = ["mmihira <mmihira.w@gmail.com>"]

[dependencies]
msg_protocol = { path= "./../msg_protocol/" }
serde_json = "1.0"
regex = "1.0.1"
names = "0.10.0"
colored = "1.6"
termion = "*"
tui = "0.2.3"
