[package]
name = "rchat"
version = "0.1.0"
authors = ["mmihira <mmihira.w@gmail.com>"]

[dependencies]
msg_protocol = { path= "./../msg_protocol/" }
serde_json = "1.0"
threadpool = "1.0"
log="0.4"
pretty_env_logger="0.2.4"
